### ISSUE TITLE
How to get the custom payload in webooks

### ISSUE THREAD

**Issue by jbmyid** [crashlytics/crashlytics-services#105]
I have to integrate the webhooks, for which I need the details of the crash like metadata of the device so that we can monitor which device is having more crash. I can't find the detail unless and untill i go to the https://www.fabric.io page.
And what is display_id is for when i can not use or get the crash details.

Please suggest any workaround if there is.

**Comment by mikebonnell** [comment]
Currently there isn't a workaround for this, but we've been discussing adding more options to the payload. I'll take you down as a +1 for this.
