### ISSUE TITLE
Jira integration with required fields

### ISSUE THREAD

**Issue by StefMa** [crashlytics/crashlytics-services#109]
We have some required fields in our jira.
For example we need always the field "version" and "customfield_xxxx". Without them, we can't create an issue.
It would be nice if we can configure the jira-hook with required fields.

Crashlytics-services doesn't support this at the moment.
It would be great if some one can make this possible :+1: :innocent:

**Comment by mikebonnell** [comment]
Hey @StefMa,

Thanks for the feedback! This is something that we've talked about adding, but isn't on our immediate roadmap. I'll let you know if that changes and keep the feedback coming :) 

-Mike
