### ISSUE TITLE
Set JIRA Issue Type ID

### ISSUE THREAD

**Issue by bassrock** [crashlytics/crashlytics-services#110]
Currently the JIRA integration only uses the issue type of 1. However that issue type does not exist on my JIRA Server. Is there a way to update the JIRA Service to support at the very least a field to set the Issue ID Type.

**Comment by mikebonnell** [comment]
Hey @bassrock,

Thanks for reaching out on this. As you mentioned, we do need an issue type of 1 to create new issues in JIRA. Adding in support to customize this is something that we're looking into, but I don't have a timeline for this currently. I'll re-open this if the work to add this is taken on, but thanks again for raising this up!

-Mike

**Comment by AlessandroLacroce** [comment]
We are experiencing the same problem. With JIRA Cloud you cannot set your own ID, so it is impossible to connect. It would be very useful (and, probably, very simple) to add a field for the issue id type.

**Comment by mikebonnell** [comment]
Thanks @AlessandroLacroce

**Comment by pm-dev** [comment]
@mikebonnell Tested out that pull request and looks like it'll work. Let me know if you're able to merge in the near future.

**Comment by jladieu** [comment]
We're hoping to provide a resolution for this issue soon, will update this issue with status as we make progress.

**Comment by pm-dev** [comment]
Thanks.

**Comment by jladieu** [comment]
A fix for this issue has been deployed.  Now Jira integrations will use issueType:name 'Bug' by default, but if you have problems with this, you can provide an override in the Jira setup UI on the Fabric dashboard.  Thanks for bringing this to our attention!

**Comment by pm-dev** [comment]
Just tried it out and works great. Thanks.
