### ISSUE TITLE
Get platform / iOS version from payload?

### ISSUE THREAD

**Issue by ablock** [crashlytics/crashlytics-services#19]
Hey, is it possible to get the platform and version distribution information from the payload so these can be included in service integrations? It looks like this isn't there now; can it be added?

Thanks!

**Comment by StefMa** [comment]
I think this can be closed, because actually we get the platform from payload.
I've tested it via [WebHooks](http://support.crashlytics.com/knowledgebase/articles/102391-how-do-i-configure-a-custom-web-hook) and we get it with json like this:
```
{"payload" : { "app" : { "platform" : "iOS" }}}
```

**Comment by jladieu** [comment]
Thanks @stefma for pointing this out.  Including OS version isn't available at this time because an issue can span multiple versions of the OS and this information isn't available in this rollup view that we provide at the issue level.  Closing this out for now.
