### ISSUE TITLE
HipChat integration may be out of date

### ISSUE THREAD

**Issue by xingrz** [crashlytics/crashlytics-services#52]
Hi,

I just failed to integrate my Crashlytics with HipChat. It just display:

```
Could not send a message to room
```

After [some investigations](https://github.com/crashlytics/crashlytics-services/blob/master/service.gemspec#L27) I've found this repo is still using gem `'hipchat', '~> 0.7'` which [uses HipChat API V1](https://github.com/hipchat/hipchat-rb/blob/v0.7.0/lib%2Fhipchat.rb#L14).

I found that [HipChat API is now in V2](https://www.hipchat.com/docs/apiv2/method/send_room_notification) and this may be the reason I failed to integrate.

Sorry that since I'm not familiar with Ruby so I couldn't ensure what's the problem exactly. Would anyone fix this? Thanks!

**Comment by seandc** [comment]
@xingrz I believe we worked this issue out with you through support a long time ago, so I'd like to close this issue.  Let me know if I'm mistaken and should keep the issue open.  Thanks!

**Comment by xingrz** [comment]
@seandc I'm afraid this issue isn't solved yet. Crashlytics still using HipChat API version 1, which is deprecated. Please upgrade it to version 2 if possible.

**Comment by seandc** [comment]
@xingrz I just created #68 which adds support for choosing API v2.  I expect to merge this tomorrow.  Thanks for your patience!  Please don't hesitate to ping me through Github or contact Fabric support if you have unresolved issues.

**Comment by seandc** [comment]
This change is in production now.  Let me know if it works for you.  Thanks!

**Comment by xingrz** [comment]
@seandc It still dosen't work.

I've checked both [crashlytics'](https://github.com/crashlytics/crashlytics-services/blob/master/lib/services/hipchat.rb#L60) and [hipchat-rb's](https://github.com/hipchat/hipchat-rb/blob/master/lib/hipchat/room.rb#L109) code but didn't find what's wrong. I emulated the HTTP request with curl, it's working.

**Comment by seandc** [comment]
@xingrz I believe I understand what the issue is and will look into it more first thing tomorrow.

**Comment by seandc** [comment]
@xingrz This should be fixed now.  Let me know how it works for you.

Thanks again!

**Comment by xingrz** [comment]
@seandc It works. Thank you very much!

**Comment by inteist** [comment]
Couldn't get the V2 to work. When removed the checkbox from "use v2 of the API" it worked fine. But since V1 is deprecated, I would like to use V2. Any idea what I am doing wrong?

**Comment by seandc** [comment]
Hi @inteist!  If it worked when you removed the checkbox, then you probably have a v1 token.  If you want a room specific API v2 token, go to `[your HipChat url]/rooms` and click the room you want to send notifications to.  You should see a `Tokens` link on the side.  If you want a general API v2 token you should be able to find it at `[your HipChat url]/account/api`.  Let me know if using one of those tokens fixes it!
