### ISSUE TITLE
Request: Gitlab integration

### ISSUE THREAD

**Issue by NerdYouDontKnow** [crashlytics/crashlytics-services#55]
Integrate with the popular Gitlab application.

API Docs: https://github.com/gitlabhq/gitlabhq/tree/master/doc/api

**Comment by bespider** [comment]
+1

**Comment by jeremydurham** [comment]
I've posted #63 to address this issue. We're working to get this merged as soon as possible.

**Comment by jeremydurham** [comment]
GitLab support has been merged! Please let us know if you run into any issues.

**Comment by xbezdeka** [comment]
Hi, I'm not able to integrate crashlytics into our company's gitlab. It always says "Could not access project....". Do you know what could be the problem? Also do I need to set up something inside gitlab (other than to get the private key)?

**Comment by mikebonnell** [comment]
Hey @xbezdeka , Mike here. Send me a note at support@ with the URL you're adding and I'll take a look.

**Comment by xbezdeka** [comment]
I not sure what you mean by "support@", is it an incomplete email adress or some kind of nick to use on github conversation?:)

**Comment by mikebonnell** [comment]
It's the shortened version of our contact. The full one is support (at) crashlytics (dot) com
