### ISSUE TITLE
Regex for jira connection wrong ? 

### ISSUE THREAD

**Issue by pmaccamp** [crashlytics/crashlytics-services#72]
Hi,
After getting repeated 'Oops! Is your project url correct?' errors I decided to look at the source and noticed the regex for determining the jira url and project appears to be wrong (or maybe I'm stupid and used the wrong url).  My url when I click on a project is 

https://mycompany.atlassian.net/projects/EIA

and I'm guessing it used to be 

https://mycompany.atlassian.net/browse/EIA

on older versions of jira.

Maybe worth update the regex from 
```
 result = { :url_prefix => url.match(/(https?:\/\/.*?)\/browse\//)[1],
      :project_key => uri.path.match(/\/browse\/(.+?)(\/|$)/)[1]}
```
to 
```
 result = { :url_prefix => url.match(/(https?:\/\/.*?)\/.+\//)[1],
      :project_key => uri.path.match(/\/.+\/(.+?)(\/|$)/)[1]}
```
to handle different JIRA versions?

Regardless hopefully this helps anyone else that may run into this.

**Comment by seandc** [comment]
Thanks for opening this issue @pmaccamp!  Sorry that the integration didn't work for you right away.  We'll look into making the regex more flexible.

**Comment by jladieu** [comment]
@pmaccamp This is all set, thanks for bringing this to our attention!
