### ISSUE TITLE
Jira components / labels

### ISSUE THREAD

**Issue by Kignuf** [crashlytics/crashlytics-services#86]
Hello there.

My company is using fabric.io and jira, but the link between the two was never configured.
I tried it today to realise that it seems there are missing options.
We are using jira component/s and labels fields to help triaging issues. For each project there are 2 components, one for the iOS app, one for the Android app.
I had a quick look at the source code and couldn't find any occurence of component or labels fields. Since they are also absent from the configuration UI, this makes sense.

I'm rather half a developper myself and never worked with Ruby yet. That being said, I'm motivated enough to explore the ways I could get this done, being it by myself or with some help.

Before I get fully started, is there anyone that could give me some hint ?
I'm not even sure such change would be acceptable for you guys ?

If I'm going into the wrong direction, please let me know !

Thanks for reading.

Kevin Roulleau
QA Manager at Webedia

**Comment by jladieu** [comment]
Hi Kevin, thank you so much for your feature suggestion.  I'll bring this to the team and we'll chat about it internally.  To get up and running now, I think if you make those fields optional in your Jira configuration you should be able to use the existing integration.  Alternately, if you don't want to change that policy in your main JIRA project, you could set up a new JIRA project for issues to flow into and then move them into the desired project after adding the component field.  I hope this helps get you to get started with the integration in the meantime.

**Comment by Kignuf** [comment]
Hello, thanks for the quick reply.

I already set up the Jira link with one of the apps and it worked fine. However this is rather useless as there are more than 20 apps to monitor. With current implementation I'm completely unable to distinguish which crash comes from where.

The best workaround I could think of would be to create one specific jira user for each app, but as you know Jira users come with a cost and I don't think Jira admins will let me do that ;-)

I tried setting up ruby, pulling the repo and making the current implementation work, but I'm really starting from 0 here and am not sure what kind of result to expect.
Having worked a little bit with Jira REST api the past, it sounds like the change itself should be rather trivial. It's just a matter of adding the two fields to the UI and sending the values during the POST. Would the thing be done in node js I probably would already have something working ;-)

**Comment by mikebonnell** [comment]
Thanks for the feedback on this! I know some other developers have used different JIRA projects to differentiate out issues from different apps. That may be easier to get by the JIRA Admins. 

We would need to add the UI changes on our end and as my colleague mentioned, we're going to chat about this internally. One of the main issues here is that within JIRA there are many configurable fields that could be made optional or not. Will definitely share your thoughts on this with the team :)

**Comment by Kignuf** [comment]
Hello Mike,
Thanks for the follow up.

Unfortunately it's not really a problem of jira administration. It simply doesn't make sense to duplicate all the projects just to have the crashlytics link to work. The whole system is already setup around the use of components, and more importantly people have their habits.

I have no clue as to how popular are components and labels fields throughout all the different jira installs worldwide. But those fields are part of the default jira installation and, I don't know how to say it in a better way but basically they "make a lot of sense" for this use case.

Hopes that convinces the team ;)

Wish you all a nice day.

**Comment by mikebonnell** [comment]
Thanks for the additional thoughts on this, will definitely share this well. 

I'm going to close this for now and will keep you updated on any changes.
