### ISSUE TITLE
\n bug in jira

### ISSUE THREAD

**Issue by Kignuf** [crashlytics/crashlytics-services#87]
Hello again,

Just to let you know I'm experiencing the following issue with the Jira integration:
![crashlytics_jira_interface_bug](https://cloud.githubusercontent.com/assets/12612344/7832008/fe21ee14-045b-11e5-8b15-e8c54cf43721.png)

I'm using jira 6.4.4

Let me know if you need any more information.

**Comment by jladieu** [comment]
@kignuf - Thanks so much for bringing this to our attention!  We'll get this fixed up and close this issue out once it's resolved.

**Comment by jladieu** [comment]
This is all set now, thanks for reporting this!
